#!/bin/bash

  echo "Enter the !st number:"
  read num1

  echo "Enter the 2nd number"
  read num2

  echo "Select the operation(+, -, *, /):"
  read op

  if ["$op" == "+"]; then
      result=$((num1 + num2))
  elif ["$op" == "-"]; then
        result=$((num1 - num2))

  elif ["$op" == "*"]; then
        result=$((num1 * num2))

  elif ["$op" == "/"]; then
        result=$((num1 / num2))

fi
echo "The result is: $result"
